### ISSUE TITLE
Merge improvements to the generator script 

### ISSUE THREAD

**Issue by m-seldin** [eedevops/generator-hubot-enterprise#22]
Please merge the following branch into master.
https://github.com/eedevops/generator-hubot-enterprise/tree/feature/generation_improvements

**Comment by rqc** [comment]
@m-seldin Awesome and thanks! I am on holiday returning Monday of next week. I will take a look.

In the meantime create a PR with a list of the features / changes (so that I have the context of the work that you did for us) and make sure that you run this through a _linter_. 

Thanks!

**Comment by m-seldin** [comment]
https://github.com/eedevops/generator-hubot-enterprise/pull/24

**Comment by m-seldin** [comment]
Hi Ricardo, please merge this pull request , it is very important for storm runner bot.
https://github.com/eedevops/generator-hubot-enterprise/pull/24

**Comment by rqc** [comment]
@m-seldin I understand the urgency. We are taking care of a different feature right now of higher priority. As you know we have reduced capacity right now and we are doing our best to accommodate all of our customers. 😅 

Review should not take too long, but it needs to be carefully executed since it could have repercussions on other items that you guys might not be using (e.g. containerized environments) since we have some interdependencies with the generator on those. 

I really appreciate your patience on this! 😄

**Comment by m-seldin** [comment]
https://github.com/eedevops/generator-hubot-enterprise/pull/25

**Comment by m-seldin** [comment]
Created pull request into master
https://github.com/eedevops/generator-hubot-enterprise/pull/26

**Comment by m-seldin** [comment]
thanks!
